{
	"version": 1675586749,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg1.png",
		"images/area1.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/player-sheet3.png",
		"images/player-sheet4.png",
		"images/player-sheet5.png",
		"images/player-sheet6.png",
		"images/player-sheet7.png",
		"images/player-sheet8.png",
		"images/player-sheet9.png",
		"images/wall1.png",
		"images/enemy1-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/backgroundui.png",
		"images/playbutton.png",
		"images/restartbutton.png",
		"images/unmutebutton.png",
		"images/mutebutton.png",
		"images/howtobutton.png",
		"images/homebutton.png",
		"images/title.png",
		"images/panel.png",
		"images/labelbar.png",
		"images/background.png",
		"images/bgprogress.png",
		"images/textable.png",
		"images/shieldup-sheet0.png",
		"images/waterup-sheet0.png",
		"images/shield-sheet0.png",
		"images/cover-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/bg2.png",
		"images/area2.png",
		"images/wall2.png",
		"media/game over.ogg",
		"media/game succes or level up.ogg",
		"media/hit enemy.ogg",
		"media/item2.ogg",
		"media/bgm (mp3cut.net).ogg",
		"media/bgm (mp3cut.net) (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"transisi.mp4"
	]
}